### ISSUE TITLE
What does |d() do?

### ISSUE THREAD

**Issue by max-b** [debops/ansible-snmpd#3]
In a variety of locations, you use notations like:
tasks/main.yml line: 47: ```when: snmpd_download_mibs|d() and snmpd_download_mibs```

tasks/main.yml line 59: ```  if (ansible_local|d() and ansible_local.snmpd|d() and
                                          ansible_local.snmpd.username)```

It looks to me like a custom filter, but I don't know where it's being pulled from... Am I missing something?

Thanks!

**Comment by drybjed** [comment]
d() is an equivalent of default() in Jinja and is used to avoid Ansible
erroring if a variable is not set.
3 lip 2015 15:09 "max-b" <notifications@github.com> napisał(a):

**Comment by max-b** [comment]
Terrific - thanks for the quick reply.
