### ISSUE TITLE
Lookup function for snmpd_account_admin_password no digits

### ISSUE THREAD

**Issue by max-b** [debops/ansible-snmpd#4]
I ran into some trouble with cacti because the password that the playbook generated including punctuation. I was wondering if something like setting `chars=ascii_letters,digits,hexdigits` would be ok for a password in defaults/main.yml line https://github.com/debops/ansible-snmpd/blob/master/defaults/main.yml#L282 and https://github.com/debops/ansible-snmpd/blob/master/defaults/main.yml#L298 ?

**Comment by drybjed** [comment]
Sure, it could have these restrictions.
8 lip 2015 07:02 "max-b" <notifications@github.com> napisał(a):

**Comment by max-b** [comment]
Closed with https://github.com/debops/ansible-snmpd/pull/5

Thanks!
